/**
 * lib/database.types.ts — Supabase Database Type Definitions
 *
 * This file defines the TypeScript types that mirror our Supabase database schema.
 * In a production workflow, you'd generate this automatically using the Supabase CLI:
 *   npx supabase gen types typescript --project-id your-project-id > src/lib/database.types.ts
 *
 * We define it manually here for clarity and to keep things self-contained.
 * The `Database` type is passed as a generic to createClient() in supabase.ts,
 * which gives us autocomplete for table names, column names, and return types.
 *
 * If you add columns to your Supabase tables, update this file to match.
 */

export type Database = {
  public: {
    Tables: {

      // ─── tasks table ────────────────────────────────────────────────────────
      tasks: {
        /**
         * Row — the shape of a single row when reading from the table.
         * These are all the columns we SELECT from `tasks`.
         */
        Row: {
          id:          string           // uuid, primary key
          title:       string           // text, not null
          description: string | null    // text, nullable
          status:      string           // text: 'todo' | 'in_progress' | 'in_review' | 'done'
          priority:    string           // text: 'high' | 'normal' | 'low'
          due_date:    string | null    // date as ISO string 'YYYY-MM-DD', nullable
          labels:      string[]         // text[], default '{}'
          user_id:     string           // uuid, references auth.users(id)
          created_at:  string           // timestamptz, default now()
        }

        /**
         * Insert — the shape of data when inserting a new row.
         * Fields with DB defaults are optional here:
         *   - id: optional (generated by gen_random_uuid())
         *   - labels: optional (defaults to '{}')
         *   - created_at: optional (defaults to now())
         *   - user_id: optional (set by RLS policy via auth.uid())
         */
        Insert: {
          id?:          string
          title:        string
          description?: string | null
          status:       string
          priority:     string
          due_date?:    string | null
          labels?:      string[]
          user_id?:     string
          created_at?:  string
        }

        /**
         * Update — the shape of data when updating an existing row.
         * All fields are optional — you only send what you're changing.
         * We never update user_id or created_at.
         */
        Update: {
          title?:       string
          description?: string | null
          status?:      string
          priority?:    string
          due_date?:    string | null
          labels?:      string[]
        }
      }

      // ─── sprints table ──────────────────────────────────────────────────────
      sprints: {
        Row: {
          id:          string
          name:        string           // e.g. "Sprint 3 — Season Launch"
          start_date:  string           // 'YYYY-MM-DD'
          end_date:    string           // 'YYYY-MM-DD'
          is_active:   boolean          // true = currently shown in the sprint banner
          user_id:     string
          created_at:  string
        }

        Insert: {
          id?:         string
          name:        string
          start_date:  string
          end_date:    string
          is_active?:  boolean          // defaults to true
          user_id?:    string
          created_at?: string
        }

        Update: {
          name?:       string
          start_date?: string
          end_date?:   string
          is_active?:  boolean
        }
      }
    }

    Views: {
      [_ in never]: never   // No views defined
    }

    Functions: {
      [_ in never]: never   // No RPC functions defined
    }

    Enums: {
      [_ in never]: never   // No enums (we use text columns with CHECK constraints)
    }
  }
}
