/**
 * types/index.ts — Central type definitions
 *
 * All TypeScript interfaces and types live here.
 * Importing from a single file keeps things consistent and avoids
 * circular imports. Every component, hook, and utility references these.
 *
 * These types mirror the Supabase database schema exactly.
 * If you add a column to the DB, add it here too.
 */


// ─── Task Status ──────────────────────────────────────────────────────────────

/**
 * TaskStatus represents which Kanban column a task lives in.
 * These string values are stored directly in Supabase — the `status` column
 * uses these exact strings, enforced by a CHECK constraint in the DB.
 *
 * Order matters here — we use this to determine column order on the board.
 */
export type TaskStatus = 'todo' | 'in_progress' | 'in_review' | 'done'

/**
 * Column definitions — maps each status to a human-readable label.
 * Used to render the column headers on the board.
 */
export const COLUMNS: { id: TaskStatus; label: string }[] = [
  { id: 'todo',        label: 'To Do' },
  { id: 'in_progress', label: 'In Progress' },
  { id: 'in_review',   label: 'In Review' },
  { id: 'done',        label: 'Done' },
]


// ─── Task Priority ────────────────────────────────────────────────────────────

/**
 * TaskPriority — the urgency level of a task.
 * Rendered as a colored dot on the task card:
 *   high   → red
 *   normal → amber
 *   low    → green
 */
export type TaskPriority = 'high' | 'normal' | 'low'

/**
 * Priority config — maps priority to display metadata.
 * Centralizing this means changing a color updates everywhere automatically.
 */
export const PRIORITY_CONFIG: Record<TaskPriority, { label: string; color: string; dotColor: string }> = {
  high:   { label: 'High',   color: 'text-red-400',    dotColor: 'bg-red-500' },
  normal: { label: 'Normal', color: 'text-amber-400',  dotColor: 'bg-amber-500' },
  low:    { label: 'Low',    color: 'text-green-400',  dotColor: 'bg-green-500' },
}


// ─── Task ─────────────────────────────────────────────────────────────────────

/**
 * Task — the core data entity in the app.
 *
 * This mirrors the `tasks` table in Supabase exactly.
 * All fields are required except those that can be null in the DB.
 */
export interface Task {
  /** UUID primary key — generated by Supabase on insert */
  id: string

  /** The task title — required, shown prominently on the card */
  title: string

  /** Longer description — optional, shown in the task detail modal */
  description: string | null

  /** Which Kanban column this task is in */
  status: TaskStatus

  /** Urgency level — rendered as a colored dot */
  priority: TaskPriority

  /** Optional due date — used for overdue/soon badges */
  due_date: string | null   // ISO 8601 date string: 'YYYY-MM-DD'

  /**
   * The Supabase auth user ID of the guest who created this task.
   * Set automatically on insert using auth.uid() via RLS.
   * Used by Row Level Security to ensure users only see their own tasks.
   */
  user_id: string

  /**
   * Optional array of label strings.
   * Stored as a Postgres text[] array column.
   * Example: ['Bug', 'Frontend', 'Urgent']
   */
  labels: string[]

  /** ISO 8601 timestamp — auto-set by Supabase via DEFAULT now() */
  created_at: string
}

/**
 * NewTask — the shape of data when creating a task.
 * Omits fields that Supabase generates automatically:
 *   - id (generated UUID)
 *   - user_id (set by RLS policy using auth.uid())
 *   - created_at (set by DEFAULT now())
 */
export type NewTask = Omit<Task, 'id' | 'user_id' | 'created_at'>

/**
 * TaskUpdate — partial task for updates.
 * Only the fields that can be changed after creation.
 * We don't allow updating user_id or created_at.
 */
export type TaskUpdate = Partial<Omit<Task, 'id' | 'user_id' | 'created_at'>>


// ─── Sprint ───────────────────────────────────────────────────────────────────

/**
 * Sprint — represents the current active sprint/milestone.
 *
 * This is stored in a separate `sprints` table in Supabase.
 * There's only ever one "active" sprint per user (is_active = true).
 * The sprint banner in the header shows progress toward the end date.
 */
export interface Sprint {
  id: string
  name: string          // e.g. "Sprint 3 — Season Launch"
  start_date: string    // ISO 8601 date: 'YYYY-MM-DD'
  end_date: string      // ISO 8601 date: 'YYYY-MM-DD'
  user_id: string
  is_active: boolean
  created_at: string
}

/**
 * NewSprint — data needed to create a sprint.
 * user_id and created_at are handled by Supabase.
 */
export type NewSprint = Omit<Sprint, 'id' | 'user_id' | 'created_at'>


// ─── Board State ──────────────────────────────────────────────────────────────

/**
 * BoardState — the shape of our main board data context.
 * Groups tasks by their status column for efficient rendering.
 *
 * Example:
 * {
 *   todo: [task1, task2],
 *   in_progress: [task3],
 *   in_review: [],
 *   done: [task4, task5, task6]
 * }
 */
export type BoardState = Record<TaskStatus, Task[]>


// ─── Filter State ─────────────────────────────────────────────────────────────

/**
 * FilterState — what the user has selected in the search/filter bar.
 * Applied client-side to the tasks array before rendering.
 */
export interface FilterState {
  /** Search string — matched against task title (case-insensitive) */
  search: string

  /**
   * Priority filter — 'all' means show everything.
   * Otherwise only tasks with this priority are shown.
   */
  priority: TaskPriority | 'all'

  /**
   * Label filter — '' means show all.
   * Otherwise only tasks with this label in their labels[] array are shown.
   */
  label: string
}


// ─── UI State ─────────────────────────────────────────────────────────────────

/**
 * DragState — tracks the currently dragged task.
 * Used by dnd-kit to render the drag overlay and handle drops.
 */
export interface DragState {
  /** The task being dragged — null when nothing is being dragged */
  activeTask: Task | null
}
